/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created: Tue 31. May 14:14:53 2011
**      by: Qt User Interface Compiler version 4.7.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QComboBox>
#include <QtGui/QFrame>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QLineEdit>
#include <QtGui/QMainWindow>
#include <QtGui/QMenuBar>
#include <QtGui/QProgressBar>
#include <QtGui/QPushButton>
#include <QtGui/QStatusBar>
#include <QtGui/QTextEdit>
#include <QtGui/QToolBar>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QFrame *frame;
    QLabel *Id_Sample;
    QLabel *Id_Year;
    QLabel *Id_Hour;
    QLineEdit *L_Sample;
    QLineEdit *L_Date;
    QLineEdit *L_Time;
    QLabel *Id_WBC_bubble;
    QLabel *Id_WBC_clog;
    QLabel *Id_RBC_bubble;
    QLabel *Id_LOW;
    QLabel *Id_RBC_clog;
    QLineEdit *L_GRAN_2;
    QLabel *Id_MID;
    QLineEdit *L_RDW_SD;
    QLabel *Id_MID_2;
    QLabel *Id_MPV;
    QLabel *Id_RDW_SD;
    QLineEdit *L_RDW_CV;
    QLabel *Id_MCV;
    QLineEdit *L_PDW;
    QLineEdit *L_MPV;
    QLineEdit *L_MID_2;
    QLabel *Id_P_LCR;
    QLabel *Id_PLT;
    QLabel *Id_GRAN_2;
    QLineEdit *L_HGB;
    QLabel *Id_PDW;
    QLabel *Id_LYM_2;
    QLabel *Id_LYM;
    QLineEdit *L_LYM_2;
    QLabel *Id_MCHC;
    QLabel *Id_HCT;
    QLineEdit *L_WBC;
    QLineEdit *L_GRAN;
    QLineEdit *L_MCV;
    QLabel *Id_PCT;
    QLabel *Id_RDW_CV;
    QLineEdit *L_MCHC;
    QLabel *Id_RBC;
    QLabel *Id_MCH;
    QLineEdit *L_PCT;
    QLineEdit *L_MID;
    QLabel *Id_HGB;
    QLineEdit *L_RBC;
    QLineEdit *L_HCT;
    QLineEdit *L_PLT;
    QLabel *Id_GRAN;
    QLineEdit *L_MCH;
    QLineEdit *L_LYM;
    QLabel *Id_WBC;
    QLineEdit *L_P_LCR;
    QLabel *Id_R2;
    QLabel *Id_R3;
    QLabel *Id_R4;
    QLabel *Id_R1;
    QLabel *Id_RM;
    QLabel *Id_PM;
    QLabel *Alarm1;
    QLabel *Alarm1_2;
    QLabel *Alarm1_3;
    QLabel *Alarm1_4;
    QLabel *Alarm1_5;
    QLabel *Alarm1_6;
    QLabel *Alarm1_7;
    QLabel *Alarm1_8;
    QLabel *Alarm1_9;
    QLabel *Alarm1_10;
    QLabel *Alarm1_11;
    QLabel *Alarm1_12;
    QLabel *Alarm1_13;
    QLabel *Alarm1_14;
    QLabel *Alarm1_15;
    QLabel *Alarm1_16;
    QLabel *Alarm1_17;
    QLabel *Alarm1_18;
    QLabel *Alarm1_19;
    QLabel *Alarm1_20;
    QLabel *Alarm1_21;
    QLabel *Alarm1_22;
    QLabel *Alarm1_23;
    QLabel *Alarm1_24;
    QLabel *Alarm1_25;
    QLabel *Alarm1_26;
    QLabel *Alarm1_27;
    QLabel *Alarm1_28;
    QLabel *Alarm1_29;
    QLabel *Alarm1_30;
    QLabel *Alarm1_31;
    QLabel *Id_PORT_COM;
    QLineEdit *L_PORT_COM;
    QPushButton *GO;
    QProgressBar *progressBar;
    QFrame *frame_to_hide;
    QLineEdit *L_Last_name;
    QLabel *SEX;
    QLineEdit *L_First_name;
    QLabel *Patient_id;
    QLineEdit *L_Birth;
    QLabel *COMMENTS;
    QLineEdit *L_Patient_id;
    QComboBox *L_Sex;
    QLabel *LAST_NAME;
    QTextEdit *L_Comm;
    QLabel *FIRST_NAME;
    QLabel *BIRTHDATE;
    QMenuBar *menuBar;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(1238, 753);
        QIcon icon;
        icon.addFile(QString::fromUtf8(":/common/imgs/common/imgs/9327.jpg"), QSize(), QIcon::Normal, QIcon::Off);
        MainWindow->setWindowIcon(icon);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        frame = new QFrame(centralWidget);
        frame->setObjectName(QString::fromUtf8("frame"));
        frame->setGeometry(QRect(20, 50, 1201, 631));
        frame->setMaximumSize(QSize(16777215, 16777215));
        frame->setFrameShape(QFrame::StyledPanel);
        frame->setFrameShadow(QFrame::Plain);
        frame->setLineWidth(1);
        Id_Sample = new QLabel(frame);
        Id_Sample->setObjectName(QString::fromUtf8("Id_Sample"));
        Id_Sample->setGeometry(QRect(10, 8, 81, 16));
        Id_Year = new QLabel(frame);
        Id_Year->setObjectName(QString::fromUtf8("Id_Year"));
        Id_Year->setGeometry(QRect(10, 38, 41, 16));
        Id_Hour = new QLabel(frame);
        Id_Hour->setObjectName(QString::fromUtf8("Id_Hour"));
        Id_Hour->setGeometry(QRect(10, 68, 51, 16));
        L_Sample = new QLineEdit(frame);
        L_Sample->setObjectName(QString::fromUtf8("L_Sample"));
        L_Sample->setGeometry(QRect(100, 8, 113, 22));
        L_Date = new QLineEdit(frame);
        L_Date->setObjectName(QString::fromUtf8("L_Date"));
        L_Date->setGeometry(QRect(100, 38, 113, 22));
        L_Time = new QLineEdit(frame);
        L_Time->setObjectName(QString::fromUtf8("L_Time"));
        L_Time->setGeometry(QRect(100, 68, 113, 22));
        Id_WBC_bubble = new QLabel(frame);
        Id_WBC_bubble->setObjectName(QString::fromUtf8("Id_WBC_bubble"));
        Id_WBC_bubble->setGeometry(QRect(780, 40, 101, 16));
        Id_WBC_clog = new QLabel(frame);
        Id_WBC_clog->setObjectName(QString::fromUtf8("Id_WBC_clog"));
        Id_WBC_clog->setGeometry(QRect(780, 70, 101, 16));
        Id_RBC_bubble = new QLabel(frame);
        Id_RBC_bubble->setObjectName(QString::fromUtf8("Id_RBC_bubble"));
        Id_RBC_bubble->setGeometry(QRect(780, 100, 81, 16));
        Id_LOW = new QLabel(frame);
        Id_LOW->setObjectName(QString::fromUtf8("Id_LOW"));
        Id_LOW->setGeometry(QRect(780, 10, 111, 16));
        Id_RBC_clog = new QLabel(frame);
        Id_RBC_clog->setObjectName(QString::fromUtf8("Id_RBC_clog"));
        Id_RBC_clog->setGeometry(QRect(780, 130, 81, 16));
        L_GRAN_2 = new QLineEdit(frame);
        L_GRAN_2->setObjectName(QString::fromUtf8("L_GRAN_2"));
        L_GRAN_2->setGeometry(QRect(273, 186, 61, 22));
        Id_MID = new QLabel(frame);
        Id_MID->setObjectName(QString::fromUtf8("Id_MID"));
        Id_MID->setGeometry(QRect(220, 156, 51, 16));
        L_RDW_SD = new QLineEdit(frame);
        L_RDW_SD->setObjectName(QString::fromUtf8("L_RDW_SD"));
        L_RDW_SD->setGeometry(QRect(453, 187, 61, 22));
        Id_MID_2 = new QLabel(frame);
        Id_MID_2->setObjectName(QString::fromUtf8("Id_MID_2"));
        Id_MID_2->setGeometry(QRect(220, 66, 51, 16));
        Id_MPV = new QLabel(frame);
        Id_MPV->setObjectName(QString::fromUtf8("Id_MPV"));
        Id_MPV->setGeometry(QRect(583, 38, 51, 16));
        Id_RDW_SD = new QLabel(frame);
        Id_RDW_SD->setObjectName(QString::fromUtf8("Id_RDW_SD"));
        Id_RDW_SD->setGeometry(QRect(400, 188, 61, 16));
        L_RDW_CV = new QLineEdit(frame);
        L_RDW_CV->setObjectName(QString::fromUtf8("L_RDW_CV"));
        L_RDW_CV->setGeometry(QRect(453, 217, 61, 22));
        Id_MCV = new QLabel(frame);
        Id_MCV->setObjectName(QString::fromUtf8("Id_MCV"));
        Id_MCV->setGeometry(QRect(400, 98, 41, 16));
        L_PDW = new QLineEdit(frame);
        L_PDW->setObjectName(QString::fromUtf8("L_PDW"));
        L_PDW->setGeometry(QRect(633, 68, 61, 22));
        L_MPV = new QLineEdit(frame);
        L_MPV->setObjectName(QString::fromUtf8("L_MPV"));
        L_MPV->setGeometry(QRect(633, 38, 61, 22));
        L_MID_2 = new QLineEdit(frame);
        L_MID_2->setObjectName(QString::fromUtf8("L_MID_2"));
        L_MID_2->setGeometry(QRect(273, 156, 61, 22));
        Id_P_LCR = new QLabel(frame);
        Id_P_LCR->setObjectName(QString::fromUtf8("Id_P_LCR"));
        Id_P_LCR->setGeometry(QRect(583, 128, 51, 16));
        Id_PLT = new QLabel(frame);
        Id_PLT->setObjectName(QString::fromUtf8("Id_PLT"));
        Id_PLT->setGeometry(QRect(583, 8, 51, 16));
        Id_GRAN_2 = new QLabel(frame);
        Id_GRAN_2->setObjectName(QString::fromUtf8("Id_GRAN_2"));
        Id_GRAN_2->setGeometry(QRect(220, 186, 51, 16));
        L_HGB = new QLineEdit(frame);
        L_HGB->setObjectName(QString::fromUtf8("L_HGB"));
        L_HGB->setGeometry(QRect(453, 37, 61, 22));
        Id_PDW = new QLabel(frame);
        Id_PDW->setObjectName(QString::fromUtf8("Id_PDW"));
        Id_PDW->setGeometry(QRect(583, 68, 51, 16));
        Id_LYM_2 = new QLabel(frame);
        Id_LYM_2->setObjectName(QString::fromUtf8("Id_LYM_2"));
        Id_LYM_2->setGeometry(QRect(220, 126, 51, 16));
        Id_LYM = new QLabel(frame);
        Id_LYM->setObjectName(QString::fromUtf8("Id_LYM"));
        Id_LYM->setGeometry(QRect(220, 36, 51, 16));
        L_LYM_2 = new QLineEdit(frame);
        L_LYM_2->setObjectName(QString::fromUtf8("L_LYM_2"));
        L_LYM_2->setGeometry(QRect(273, 126, 61, 22));
        Id_MCHC = new QLabel(frame);
        Id_MCHC->setObjectName(QString::fromUtf8("Id_MCHC"));
        Id_MCHC->setGeometry(QRect(400, 158, 51, 16));
        Id_HCT = new QLabel(frame);
        Id_HCT->setObjectName(QString::fromUtf8("Id_HCT"));
        Id_HCT->setGeometry(QRect(400, 68, 41, 16));
        L_WBC = new QLineEdit(frame);
        L_WBC->setObjectName(QString::fromUtf8("L_WBC"));
        L_WBC->setGeometry(QRect(273, 8, 61, 22));
        L_GRAN = new QLineEdit(frame);
        L_GRAN->setObjectName(QString::fromUtf8("L_GRAN"));
        L_GRAN->setGeometry(QRect(273, 96, 61, 22));
        L_MCV = new QLineEdit(frame);
        L_MCV->setObjectName(QString::fromUtf8("L_MCV"));
        L_MCV->setGeometry(QRect(453, 97, 61, 22));
        Id_PCT = new QLabel(frame);
        Id_PCT->setObjectName(QString::fromUtf8("Id_PCT"));
        Id_PCT->setGeometry(QRect(583, 98, 51, 16));
        Id_RDW_CV = new QLabel(frame);
        Id_RDW_CV->setObjectName(QString::fromUtf8("Id_RDW_CV"));
        Id_RDW_CV->setGeometry(QRect(400, 218, 61, 16));
        L_MCHC = new QLineEdit(frame);
        L_MCHC->setObjectName(QString::fromUtf8("L_MCHC"));
        L_MCHC->setGeometry(QRect(453, 157, 61, 22));
        Id_RBC = new QLabel(frame);
        Id_RBC->setObjectName(QString::fromUtf8("Id_RBC"));
        Id_RBC->setGeometry(QRect(400, 8, 41, 16));
        Id_MCH = new QLabel(frame);
        Id_MCH->setObjectName(QString::fromUtf8("Id_MCH"));
        Id_MCH->setGeometry(QRect(400, 128, 41, 16));
        L_PCT = new QLineEdit(frame);
        L_PCT->setObjectName(QString::fromUtf8("L_PCT"));
        L_PCT->setGeometry(QRect(633, 98, 61, 22));
        L_MID = new QLineEdit(frame);
        L_MID->setObjectName(QString::fromUtf8("L_MID"));
        L_MID->setGeometry(QRect(273, 66, 61, 22));
        Id_HGB = new QLabel(frame);
        Id_HGB->setObjectName(QString::fromUtf8("Id_HGB"));
        Id_HGB->setGeometry(QRect(400, 38, 41, 16));
        L_RBC = new QLineEdit(frame);
        L_RBC->setObjectName(QString::fromUtf8("L_RBC"));
        L_RBC->setGeometry(QRect(453, 7, 61, 22));
        L_HCT = new QLineEdit(frame);
        L_HCT->setObjectName(QString::fromUtf8("L_HCT"));
        L_HCT->setGeometry(QRect(453, 67, 61, 22));
        L_PLT = new QLineEdit(frame);
        L_PLT->setObjectName(QString::fromUtf8("L_PLT"));
        L_PLT->setGeometry(QRect(633, 8, 61, 22));
        Id_GRAN = new QLabel(frame);
        Id_GRAN->setObjectName(QString::fromUtf8("Id_GRAN"));
        Id_GRAN->setGeometry(QRect(220, 96, 51, 16));
        L_MCH = new QLineEdit(frame);
        L_MCH->setObjectName(QString::fromUtf8("L_MCH"));
        L_MCH->setGeometry(QRect(453, 127, 61, 22));
        L_LYM = new QLineEdit(frame);
        L_LYM->setObjectName(QString::fromUtf8("L_LYM"));
        L_LYM->setGeometry(QRect(273, 36, 61, 22));
        Id_WBC = new QLabel(frame);
        Id_WBC->setObjectName(QString::fromUtf8("Id_WBC"));
        Id_WBC->setGeometry(QRect(220, 8, 51, 16));
        L_P_LCR = new QLineEdit(frame);
        L_P_LCR->setObjectName(QString::fromUtf8("L_P_LCR"));
        L_P_LCR->setGeometry(QRect(633, 128, 61, 22));
        Id_R2 = new QLabel(frame);
        Id_R2->setObjectName(QString::fromUtf8("Id_R2"));
        Id_R2->setGeometry(QRect(950, 70, 31, 16));
        Id_R3 = new QLabel(frame);
        Id_R3->setObjectName(QString::fromUtf8("Id_R3"));
        Id_R3->setGeometry(QRect(950, 100, 31, 16));
        Id_R4 = new QLabel(frame);
        Id_R4->setObjectName(QString::fromUtf8("Id_R4"));
        Id_R4->setGeometry(QRect(950, 130, 41, 16));
        Id_R1 = new QLabel(frame);
        Id_R1->setObjectName(QString::fromUtf8("Id_R1"));
        Id_R1->setGeometry(QRect(950, 40, 31, 16));
        Id_RM = new QLabel(frame);
        Id_RM->setObjectName(QString::fromUtf8("Id_RM"));
        Id_RM->setGeometry(QRect(950, 10, 41, 16));
        Id_PM = new QLabel(frame);
        Id_PM->setObjectName(QString::fromUtf8("Id_PM"));
        Id_PM->setGeometry(QRect(950, 160, 41, 16));
        Alarm1 = new QLabel(frame);
        Alarm1->setObjectName(QString::fromUtf8("Alarm1"));
        Alarm1->setGeometry(QRect(340, 0, 32, 32));
        Alarm1->setStyleSheet(QString::fromUtf8(""));
        Alarm1_2 = new QLabel(frame);
        Alarm1_2->setObjectName(QString::fromUtf8("Alarm1_2"));
        Alarm1_2->setGeometry(QRect(340, 30, 32, 32));
        Alarm1_2->setStyleSheet(QString::fromUtf8(""));
        Alarm1_3 = new QLabel(frame);
        Alarm1_3->setObjectName(QString::fromUtf8("Alarm1_3"));
        Alarm1_3->setGeometry(QRect(340, 62, 32, 32));
        Alarm1_3->setStyleSheet(QString::fromUtf8(""));
        Alarm1_4 = new QLabel(frame);
        Alarm1_4->setObjectName(QString::fromUtf8("Alarm1_4"));
        Alarm1_4->setGeometry(QRect(340, 93, 32, 32));
        Alarm1_4->setStyleSheet(QString::fromUtf8(""));
        Alarm1_5 = new QLabel(frame);
        Alarm1_5->setObjectName(QString::fromUtf8("Alarm1_5"));
        Alarm1_5->setGeometry(QRect(340, 123, 32, 32));
        Alarm1_5->setStyleSheet(QString::fromUtf8(""));
        Alarm1_6 = new QLabel(frame);
        Alarm1_6->setObjectName(QString::fromUtf8("Alarm1_6"));
        Alarm1_6->setGeometry(QRect(340, 152, 32, 32));
        Alarm1_6->setStyleSheet(QString::fromUtf8(""));
        Alarm1_7 = new QLabel(frame);
        Alarm1_7->setObjectName(QString::fromUtf8("Alarm1_7"));
        Alarm1_7->setGeometry(QRect(340, 182, 32, 32));
        Alarm1_7->setStyleSheet(QString::fromUtf8(""));
        Alarm1_8 = new QLabel(frame);
        Alarm1_8->setObjectName(QString::fromUtf8("Alarm1_8"));
        Alarm1_8->setGeometry(QRect(520, 4, 32, 32));
        Alarm1_8->setStyleSheet(QString::fromUtf8(""));
        Alarm1_9 = new QLabel(frame);
        Alarm1_9->setObjectName(QString::fromUtf8("Alarm1_9"));
        Alarm1_9->setGeometry(QRect(520, 32, 32, 32));
        Alarm1_9->setStyleSheet(QString::fromUtf8(""));
        Alarm1_10 = new QLabel(frame);
        Alarm1_10->setObjectName(QString::fromUtf8("Alarm1_10"));
        Alarm1_10->setGeometry(QRect(520, 62, 32, 32));
        Alarm1_10->setStyleSheet(QString::fromUtf8(""));
        Alarm1_11 = new QLabel(frame);
        Alarm1_11->setObjectName(QString::fromUtf8("Alarm1_11"));
        Alarm1_11->setGeometry(QRect(520, 92, 32, 32));
        Alarm1_11->setStyleSheet(QString::fromUtf8(""));
        Alarm1_12 = new QLabel(frame);
        Alarm1_12->setObjectName(QString::fromUtf8("Alarm1_12"));
        Alarm1_12->setGeometry(QRect(520, 122, 32, 32));
        Alarm1_12->setStyleSheet(QString::fromUtf8(""));
        Alarm1_13 = new QLabel(frame);
        Alarm1_13->setObjectName(QString::fromUtf8("Alarm1_13"));
        Alarm1_13->setGeometry(QRect(520, 152, 32, 32));
        Alarm1_13->setStyleSheet(QString::fromUtf8(""));
        Alarm1_14 = new QLabel(frame);
        Alarm1_14->setObjectName(QString::fromUtf8("Alarm1_14"));
        Alarm1_14->setGeometry(QRect(520, 182, 32, 32));
        Alarm1_14->setStyleSheet(QString::fromUtf8(""));
        Alarm1_15 = new QLabel(frame);
        Alarm1_15->setObjectName(QString::fromUtf8("Alarm1_15"));
        Alarm1_15->setGeometry(QRect(520, 212, 32, 32));
        Alarm1_15->setStyleSheet(QString::fromUtf8(""));
        Alarm1_16 = new QLabel(frame);
        Alarm1_16->setObjectName(QString::fromUtf8("Alarm1_16"));
        Alarm1_16->setGeometry(QRect(700, 4, 32, 32));
        Alarm1_16->setStyleSheet(QString::fromUtf8(""));
        Alarm1_17 = new QLabel(frame);
        Alarm1_17->setObjectName(QString::fromUtf8("Alarm1_17"));
        Alarm1_17->setGeometry(QRect(700, 32, 32, 32));
        Alarm1_17->setStyleSheet(QString::fromUtf8(""));
        Alarm1_18 = new QLabel(frame);
        Alarm1_18->setObjectName(QString::fromUtf8("Alarm1_18"));
        Alarm1_18->setGeometry(QRect(700, 62, 32, 32));
        Alarm1_18->setStyleSheet(QString::fromUtf8(""));
        Alarm1_19 = new QLabel(frame);
        Alarm1_19->setObjectName(QString::fromUtf8("Alarm1_19"));
        Alarm1_19->setGeometry(QRect(700, 92, 32, 32));
        Alarm1_19->setStyleSheet(QString::fromUtf8(""));
        Alarm1_20 = new QLabel(frame);
        Alarm1_20->setObjectName(QString::fromUtf8("Alarm1_20"));
        Alarm1_20->setGeometry(QRect(700, 122, 32, 32));
        Alarm1_20->setStyleSheet(QString::fromUtf8(""));
        Alarm1_21 = new QLabel(frame);
        Alarm1_21->setObjectName(QString::fromUtf8("Alarm1_21"));
        Alarm1_21->setGeometry(QRect(890, 4, 32, 32));
        Alarm1_21->setStyleSheet(QString::fromUtf8(""));
        Alarm1_22 = new QLabel(frame);
        Alarm1_22->setObjectName(QString::fromUtf8("Alarm1_22"));
        Alarm1_22->setGeometry(QRect(890, 34, 32, 32));
        Alarm1_22->setStyleSheet(QString::fromUtf8(""));
        Alarm1_23 = new QLabel(frame);
        Alarm1_23->setObjectName(QString::fromUtf8("Alarm1_23"));
        Alarm1_23->setGeometry(QRect(890, 64, 32, 32));
        Alarm1_23->setStyleSheet(QString::fromUtf8(""));
        Alarm1_24 = new QLabel(frame);
        Alarm1_24->setObjectName(QString::fromUtf8("Alarm1_24"));
        Alarm1_24->setGeometry(QRect(890, 94, 32, 32));
        Alarm1_24->setStyleSheet(QString::fromUtf8(""));
        Alarm1_25 = new QLabel(frame);
        Alarm1_25->setObjectName(QString::fromUtf8("Alarm1_25"));
        Alarm1_25->setGeometry(QRect(890, 124, 32, 32));
        Alarm1_25->setStyleSheet(QString::fromUtf8(""));
        Alarm1_26 = new QLabel(frame);
        Alarm1_26->setObjectName(QString::fromUtf8("Alarm1_26"));
        Alarm1_26->setGeometry(QRect(980, 3, 32, 32));
        Alarm1_26->setStyleSheet(QString::fromUtf8(""));
        Alarm1_27 = new QLabel(frame);
        Alarm1_27->setObjectName(QString::fromUtf8("Alarm1_27"));
        Alarm1_27->setGeometry(QRect(980, 33, 32, 32));
        Alarm1_27->setStyleSheet(QString::fromUtf8(""));
        Alarm1_28 = new QLabel(frame);
        Alarm1_28->setObjectName(QString::fromUtf8("Alarm1_28"));
        Alarm1_28->setGeometry(QRect(980, 63, 32, 32));
        Alarm1_28->setStyleSheet(QString::fromUtf8(""));
        Alarm1_29 = new QLabel(frame);
        Alarm1_29->setObjectName(QString::fromUtf8("Alarm1_29"));
        Alarm1_29->setGeometry(QRect(980, 93, 32, 32));
        Alarm1_29->setStyleSheet(QString::fromUtf8(""));
        Alarm1_30 = new QLabel(frame);
        Alarm1_30->setObjectName(QString::fromUtf8("Alarm1_30"));
        Alarm1_30->setGeometry(QRect(980, 123, 32, 32));
        Alarm1_30->setStyleSheet(QString::fromUtf8(""));
        Alarm1_31 = new QLabel(frame);
        Alarm1_31->setObjectName(QString::fromUtf8("Alarm1_31"));
        Alarm1_31->setGeometry(QRect(980, 153, 32, 32));
        Alarm1_31->setStyleSheet(QString::fromUtf8(""));
        Id_PORT_COM = new QLabel(centralWidget);
        Id_PORT_COM->setObjectName(QString::fromUtf8("Id_PORT_COM"));
        Id_PORT_COM->setGeometry(QRect(31, 20, 181, 16));
        L_PORT_COM = new QLineEdit(centralWidget);
        L_PORT_COM->setObjectName(QString::fromUtf8("L_PORT_COM"));
        L_PORT_COM->setGeometry(QRect(211, 18, 113, 22));
        GO = new QPushButton(centralWidget);
        GO->setObjectName(QString::fromUtf8("GO"));
        GO->setGeometry(QRect(331, 16, 41, 28));
        progressBar = new QProgressBar(centralWidget);
        progressBar->setObjectName(QString::fromUtf8("progressBar"));
        progressBar->setGeometry(QRect(1020, 17, 118, 23));
        progressBar->setValue(24);
        frame_to_hide = new QFrame(centralWidget);
        frame_to_hide->setObjectName(QString::fromUtf8("frame_to_hide"));
        frame_to_hide->setGeometry(QRect(320, 589, 120, 191));
        frame_to_hide->setFrameShape(QFrame::StyledPanel);
        frame_to_hide->setFrameShadow(QFrame::Raised);
        L_Last_name = new QLineEdit(frame_to_hide);
        L_Last_name->setObjectName(QString::fromUtf8("L_Last_name"));
        L_Last_name->setGeometry(QRect(90, 60, 113, 22));
        SEX = new QLabel(frame_to_hide);
        SEX->setObjectName(QString::fromUtf8("SEX"));
        SEX->setGeometry(QRect(30, 122, 53, 16));
        L_First_name = new QLineEdit(frame_to_hide);
        L_First_name->setObjectName(QString::fromUtf8("L_First_name"));
        L_First_name->setGeometry(QRect(90, 92, 113, 22));
        Patient_id = new QLabel(frame_to_hide);
        Patient_id->setObjectName(QString::fromUtf8("Patient_id"));
        Patient_id->setGeometry(QRect(20, 182, 61, 16));
        L_Birth = new QLineEdit(frame_to_hide);
        L_Birth->setObjectName(QString::fromUtf8("L_Birth"));
        L_Birth->setGeometry(QRect(90, 152, 113, 22));
        COMMENTS = new QLabel(frame_to_hide);
        COMMENTS->setObjectName(QString::fromUtf8("COMMENTS"));
        COMMENTS->setGeometry(QRect(20, 212, 71, 16));
        L_Patient_id = new QLineEdit(frame_to_hide);
        L_Patient_id->setObjectName(QString::fromUtf8("L_Patient_id"));
        L_Patient_id->setGeometry(QRect(90, 182, 113, 22));
        L_Sex = new QComboBox(frame_to_hide);
        L_Sex->setObjectName(QString::fromUtf8("L_Sex"));
        L_Sex->setGeometry(QRect(90, 122, 73, 22));
        LAST_NAME = new QLabel(frame_to_hide);
        LAST_NAME->setObjectName(QString::fromUtf8("LAST_NAME"));
        LAST_NAME->setGeometry(QRect(20, 62, 71, 16));
        L_Comm = new QTextEdit(frame_to_hide);
        L_Comm->setObjectName(QString::fromUtf8("L_Comm"));
        L_Comm->setGeometry(QRect(90, 212, 201, 131));
        QFont font;
        font.setPointSize(6);
        L_Comm->setFont(font);
        FIRST_NAME = new QLabel(frame_to_hide);
        FIRST_NAME->setObjectName(QString::fromUtf8("FIRST_NAME"));
        FIRST_NAME->setGeometry(QRect(20, 92, 71, 16));
        BIRTHDATE = new QLabel(frame_to_hide);
        BIRTHDATE->setObjectName(QString::fromUtf8("BIRTHDATE"));
        BIRTHDATE->setGeometry(QRect(20, 152, 61, 16));
        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QString::fromUtf8("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1238, 21));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QString::fromUtf8("mainToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QString::fromUtf8("statusBar"));
        MainWindow->setStatusBar(statusBar);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "H18 SelfExtractor", 0, QApplication::UnicodeUTF8));
        Id_Sample->setText(QApplication::translate("MainWindow", "Sample No:", 0, QApplication::UnicodeUTF8));
        Id_Year->setText(QApplication::translate("MainWindow", "Date:", 0, QApplication::UnicodeUTF8));
        Id_Hour->setText(QApplication::translate("MainWindow", "Time:", 0, QApplication::UnicodeUTF8));
        Id_WBC_bubble->setText(QApplication::translate("MainWindow", "WBC bubble:", 0, QApplication::UnicodeUTF8));
        Id_WBC_clog->setText(QApplication::translate("MainWindow", "WBC clog:", 0, QApplication::UnicodeUTF8));
        Id_RBC_bubble->setText(QApplication::translate("MainWindow", "RBC bubble:", 0, QApplication::UnicodeUTF8));
        Id_LOW->setText(QApplication::translate("MainWindow", "Low temperature:", 0, QApplication::UnicodeUTF8));
        Id_RBC_clog->setText(QApplication::translate("MainWindow", "RBC clog:", 0, QApplication::UnicodeUTF8));
        L_GRAN_2->setText(QString());
        Id_MID->setText(QApplication::translate("MainWindow", "MON#:", 0, QApplication::UnicodeUTF8));
        L_RDW_SD->setText(QString());
        Id_MID_2->setText(QApplication::translate("MainWindow", "MON%:", 0, QApplication::UnicodeUTF8));
        Id_MPV->setText(QApplication::translate("MainWindow", "MPV:", 0, QApplication::UnicodeUTF8));
        Id_RDW_SD->setText(QApplication::translate("MainWindow", "RDW-SD:", 0, QApplication::UnicodeUTF8));
        L_RDW_CV->setText(QString());
        Id_MCV->setText(QApplication::translate("MainWindow", "MCV:", 0, QApplication::UnicodeUTF8));
        L_PDW->setText(QString());
        L_MPV->setText(QString());
        L_MID_2->setText(QString());
        Id_P_LCR->setText(QApplication::translate("MainWindow", "P-LCR:", 0, QApplication::UnicodeUTF8));
        Id_PLT->setText(QApplication::translate("MainWindow", "PLT:", 0, QApplication::UnicodeUTF8));
        Id_GRAN_2->setText(QApplication::translate("MainWindow", "GRAN#:", 0, QApplication::UnicodeUTF8));
        L_HGB->setText(QString());
        Id_PDW->setText(QApplication::translate("MainWindow", "PDW:", 0, QApplication::UnicodeUTF8));
        Id_LYM_2->setText(QApplication::translate("MainWindow", "LYM#:", 0, QApplication::UnicodeUTF8));
        Id_LYM->setText(QApplication::translate("MainWindow", "LYM%:", 0, QApplication::UnicodeUTF8));
        L_LYM_2->setText(QString());
        Id_MCHC->setText(QApplication::translate("MainWindow", "MCHC:", 0, QApplication::UnicodeUTF8));
        Id_HCT->setText(QApplication::translate("MainWindow", "HCT:", 0, QApplication::UnicodeUTF8));
        L_WBC->setText(QString());
        L_GRAN->setText(QString());
        L_MCV->setText(QString());
        Id_PCT->setText(QApplication::translate("MainWindow", "PCT:", 0, QApplication::UnicodeUTF8));
        Id_RDW_CV->setText(QApplication::translate("MainWindow", "RDW-CV:", 0, QApplication::UnicodeUTF8));
        L_MCHC->setText(QString());
        Id_RBC->setText(QApplication::translate("MainWindow", "RBC:", 0, QApplication::UnicodeUTF8));
        Id_MCH->setText(QApplication::translate("MainWindow", "MCH:", 0, QApplication::UnicodeUTF8));
        L_PCT->setText(QString());
        L_MID->setText(QString());
        Id_HGB->setText(QApplication::translate("MainWindow", "HGB:", 0, QApplication::UnicodeUTF8));
        L_RBC->setText(QString());
        L_HCT->setText(QString());
        L_PLT->setText(QString());
        Id_GRAN->setText(QApplication::translate("MainWindow", "GRAN%:", 0, QApplication::UnicodeUTF8));
        L_MCH->setText(QString());
        L_LYM->setText(QString());
        Id_WBC->setText(QApplication::translate("MainWindow", "WBC:", 0, QApplication::UnicodeUTF8));
        L_P_LCR->setText(QString());
        Id_R2->setText(QApplication::translate("MainWindow", "R2:", 0, QApplication::UnicodeUTF8));
        Id_R3->setText(QApplication::translate("MainWindow", "R3:", 0, QApplication::UnicodeUTF8));
        Id_R4->setText(QApplication::translate("MainWindow", "R4:", 0, QApplication::UnicodeUTF8));
        Id_R1->setText(QApplication::translate("MainWindow", "R1:", 0, QApplication::UnicodeUTF8));
        Id_RM->setText(QApplication::translate("MainWindow", "RM:", 0, QApplication::UnicodeUTF8));
        Id_PM->setText(QApplication::translate("MainWindow", "PM:", 0, QApplication::UnicodeUTF8));
        Alarm1->setText(QString());
        Alarm1_2->setText(QString());
        Alarm1_3->setText(QString());
        Alarm1_4->setText(QString());
        Alarm1_5->setText(QString());
        Alarm1_6->setText(QString());
        Alarm1_7->setText(QString());
        Alarm1_8->setText(QString());
        Alarm1_9->setText(QString());
        Alarm1_10->setText(QString());
        Alarm1_11->setText(QString());
        Alarm1_12->setText(QString());
        Alarm1_13->setText(QString());
        Alarm1_14->setText(QString());
        Alarm1_15->setText(QString());
        Alarm1_16->setText(QString());
        Alarm1_17->setText(QString());
        Alarm1_18->setText(QString());
        Alarm1_19->setText(QString());
        Alarm1_20->setText(QString());
        Alarm1_21->setText(QString());
        Alarm1_22->setText(QString());
        Alarm1_23->setText(QString());
        Alarm1_24->setText(QString());
        Alarm1_25->setText(QString());
        Alarm1_26->setText(QString());
        Alarm1_27->setText(QString());
        Alarm1_28->setText(QString());
        Alarm1_29->setText(QString());
        Alarm1_30->setText(QString());
        Alarm1_31->setText(QString());
        Id_PORT_COM->setText(QApplication::translate("MainWindow", "Port COM (exemple \"COM1\"):", 0, QApplication::UnicodeUTF8));
        GO->setText(QApplication::translate("MainWindow", "GO", 0, QApplication::UnicodeUTF8));
        SEX->setText(QApplication::translate("MainWindow", "Sex:", 0, QApplication::UnicodeUTF8));
        Patient_id->setText(QApplication::translate("MainWindow", "Patient ID:", 0, QApplication::UnicodeUTF8));
        COMMENTS->setText(QApplication::translate("MainWindow", "Comments:", 0, QApplication::UnicodeUTF8));
        L_Sex->clear();
        L_Sex->insertItems(0, QStringList()
         << QApplication::translate("MainWindow", "-", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("MainWindow", "Homme", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("MainWindow", "Femme", 0, QApplication::UnicodeUTF8)
        );
        LAST_NAME->setText(QApplication::translate("MainWindow", "Last name:", 0, QApplication::UnicodeUTF8));
        FIRST_NAME->setText(QApplication::translate("MainWindow", "First name:", 0, QApplication::UnicodeUTF8));
        BIRTHDATE->setText(QApplication::translate("MainWindow", "Birthdate:", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
